online-shop/puddle/conversation/urls.py
from django.urls import path

from . import views

app_name = "conversation"

urlpatterns = [
    path("", views.inbox_view, name="inbox-view"),
    path("<int:pk>/", views.detail_view, name="detail-view"),
    path("new/<int:item_pk>/", views.new_view, name="new-view")
]

online-shop/puddle/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = "core"

urlpatterns = [
    path("", views.index_view, name="index-view"),
    path("contact/", views.contact_view, name="contact-view"),
    path("signup/", views.signup_view, name="signup-view"),
    path("login/", auth_views.LoginView.as_view(template_name="core/core_login.html", authentication_form=LoginForm), name="login-view")
]

online-shop/puddle/dashboard/urls.py
from django.urls import path

from . import views

app_name = "dashboard"

urlpatterns = [
    path("", views.index_view, name="index-view"),
    path("<int:pk>/category/", views.category_view, name="category-view")
]

online-shop/puddle/item/urls.py
from django.urls import path

from .views import detail_view, new_view, delete_view, edit_view, items_view

app_name = "item"

urlpatterns = [
    path("new/", new_view, name="new-view"),
    path("<int:pk>/", detail_view, name="detail-view"),
    path("<int:pk>/delete/", delete_view, name="delete-view"),
    path("<int:pk>/edit/", edit_view, name="edit-view"),
    path("", items_view, name="items-view"),
]

online-shop/puddle/puddle/urls.py
from django.contrib import admin
from django.urls import path, include
# from core.views import (
#     index_view,
#     contact_view,
#     )
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    # path("", index_view, name="index-view"),
    path("", include("core.urls")),
    # path("contact/", contact_view, name="contact_view"),
    path("dashboard/", include("dashboard.urls")),
    path("inbox/", include("conversation.urls")),

    
    path("items/", include("item.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online-shop/puddle/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):

    class Meta:
        model = User

    username = forms.CharField()
    # username = forms.CharField(widget=forms.TextInput(attrs={
    #     "placeholder": "Your username",
    #     "class": "w-full py-4 px-6 rounded-xl",    
    #     }))
    
    password = forms.CharField()
    # password = forms.CharField(widget=forms.PasswordInput(attrs={
    #     "placeholder": "Your password",
    #     "class": "w-full py-4 px-6 rounded-xl",    
    #     }))

class SignupForm(UserCreationForm):

    class Meta:
        model = User
        fields = (
            "username",
            "email",
            "password1",
            "password2")

    username = forms.CharField(widget=forms.TextInput(attrs={
        "placeholder": "Your username",
        "class": "w-full py-4 px-6 rounded-xl",    
        }))
    
    email = forms.CharField(widget=forms.EmailInput(attrs={
        "placeholder": "Your emial address",
        "class": "w-full py-4 px-6 rounded-xl",    
        }))
    
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        "placeholder": "Your password",
        "class": "w-full py-4 px-6 rounded-xl",    
        }))
    
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        "placeholder": "Repeat password",
        "class": "w-full py-4 px-6 rounded-xl",    
        }))
    

online-shop/puddle/core/views.py
from django.shortcuts import render, redirect
from item.models import Category, Item
from .forms import SignupForm

def index_view(request):
    items = Item.objects.filter(is_sold=False)[:6]
    categories = Category.objects.all()
    context = {
        "items": items,
        "categories": categories
    }
    return render(request, "core/core_index.html", context)

def contact_view(request):
    return render(request, "core/core_contact.html")

def signup_view(request):
    form = SignupForm(request.POST or None)
    context = {
        "form": form
    }
    if form.is_valid():
        form.save()
        return redirect("/login/")

    # if request.method == "POST":
    #     form = SignupForm(request.POST)
    #     if form.is_valid():
    #         form.save()
    #         return redirect("/login/")
    # else:
    #     form = SignupForm()

    return render(request, "core/core_signup.html", context)

online-shop/puddle/core/templates/core/core_base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="ute-8">
    <meta name="viewport" content="width=dewice-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>
      {% block title %}
      {% endblock title %}
    | Puddle</title>
  </head>
  <body>
    {% include "core/core_header.html" %}
    <div class="px-6 py-6">
      {% block content %}
      {% endblock content %}
    </div>
    {% include "core/core_footer.html" %}
  </body>
</html>

online-shop/puddle/core/templates/core/core_contact.html
{% extends "core/core_base.html" %}

{% block title %}Contact{% endblock title %}

{% block content %}
<h1>The contact page</h1>
{% endblock content %}

online-shop/puddle/core/templates/core/core_footer.html
{% block footer %}
<footer class="py-6 px-6 flex justify-between bg-gray-800">
    <div class="w-2/3 pr-10">
      <h3 class="mb-5 font-semibold text-gray-400">About</h3>
      <p class="text-lg text-gray-500"> Bla a oeneon eon oin ioen ion eion in ioen ioen ioen ioen </p>
    </div>
    <div class="w-1/3">
      <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
      <ul class="space-y-2">
        <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
        <li><a href="{% url "core:contact-view" %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
        <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a></li>
        <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Terms of use</a></li>
      </ul>
    </div>
</footer>
{% endblock footer %}

online-shop/puddle/core/templates/core/core_header.html
<nav class="px-6 py-6 flex justify-between items-center border-b border-gary-200">
    <a href="/" class="text-xl font-semibold">Hello {{ request.user }}</a>

    <div class="space-x-6 bg-gray-200">
      <a href="{% url 'core:index-view' %}" class="text-lg font-semibold hover:text-gray-500">Home</a>
      <a href="{% url 'item:new-view' %}" class="text-lg font-semibold hover:text-gray-500">New item</a>
      <a href="{% url 'item:items-view' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a>

      {% if request.user.is_authenticated %}
      <a href="{% url "conversation:inbox-view" %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>
      <a href="{% url "dashboard:index-view" %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dasbhoard</a>
      {% else %}
        <a href="{% url 'core:signup-view' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
        <a href="{% url 'core:login-view' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Login</a>
      {% endif %}
    </div>
</nav>

online-shop/puddle/core/templates/core/core_index.html
{% extends "core/core_base.html" %}

{% block title %}Welcome{% endblock title %}

{% block content %}

<div class="mt-6 px-6 py-12 bg-gray-200 rounded-xl">
    <h2 class="mb-12 text-2xl text-center ">Newest items</h2>
    
    <div class="grid grid-cols-3 gap-3">
        {% for item in items %}
            <div>
                <a href="{% url 'item:detail-view' item.id %}">
                    <div>
                        <img src="{{ item.image.url }}" class="rounded-t-xl"></img>
                    </div>

                    <div class="p-6 bg-gray-300 rounded-b-xl">
                        <h2 class="text-2xl">{{ item.name }}</h2>
                        <p class="text-gray-500">Price: {{ item.price }}</p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-200 rounded-xl">
    <h2 class="mb-12 text-2xl text-center ">Categories</h2>
    <div class="grid grid-cols-3 gap-3">
        {% for category in categories %}
        <div>
            <a href="#">
                <div class="p-6 bg-gray-300 rounded-b-xl">
                    <h2 class="text-2xl ">{{ category.name }}</h2>
                    <p class="text-gray-500">{{ category.items.count }} items</p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

online-shop/puddle/core/templates/core/core_login.html
{% extends 'core/core_base.html' %}

{% block title %}
  Login
{% endblock %}

{% block content %}
  <div class="w-1/2 my-6 mx-auto p-6 bg-gray-200 rounded-xl">
    <h1 class="mb-6 text-3xl font-semibold">Login</h1>
    <form method="POST" action=".">
      {% csrf_token %}

      <div class="mb-3">
        <label class="inline-block mb-2">Username</label><br />
        {{ form.username }}
      </div>

      <div class="mb-3">
        <label class="inline-block mb-2">Password</label><br />
        {{ form.password }}
      </div>

      {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
          {% for field in form %}
            {{ field.errors }}
          {% endfor %}

          {{ form.non_field_errors }}
        </div>
      {% endif %}

      <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
  </div>
{% endblock %}

online-shop/puddle/core/templates/core/core_signup.html
{% extends "core/core_base.html" %}

{% block title %}Sign up{% endblock title %}

{% block content %}
    <div class="w-1/2 my-6 mx-auto p-6 bg-gary-100 rounded-xl">
        <h1 class="mb-6 text-3xl">Sign up</h1>
        <form method="POST" action=".">{% csrf_token %}
            
            <div class="mb-3">
                <label class="inline-block mb-2">Username</label><br>
                {{ form.username }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Email</label><br>
                {{ form.email }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Password</label><br>
                {{ form.password1 }}
            </div>
            
            <div class="mb-3">
                <label class="inline-block mb-2">Repeat password</label><br>
                {{ form.password2 }}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}
                    
                {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
        </form>
    </div>
{% endblock content %}